VALUES (32, 209, 'default_3x3', 'lost_tribe', 'Verlorener Stamm', 1, 38, 1, 0, 121, '1', '1', '0', '0', '', '', '', 'losttribe', 'LT_teaser_en', 'Starten Sie Ihr eigenes Stammesdorf mit unseren antiken Möbeln, die alle aus robustem Stein geschnitzt sind. HINWEIS: Die Lava ist heiß, bitten Sie einen Erwachsenen, Ihnen zu helfen.', '', '');
INSERT INTO `catalog_pages` VALUES (33, 209, 'default_3x3', 'neon', 'Neon', 1, 41, 1, 0, 77, '1', '1', '0', '0', '', '', '', 'catalog_neon_header1_en', 'catalog_neon_teaser1_en', 'Die Partygänger freuen sich! Legen Sie den Grundstein und greifen Sie zu Lasern mit der Neon Furniture Serie – alles, was Sie brauchen, um die Party zu beginnen!', '', '');
INSERT INTO `catalog_pages` VALUES (34, 209, 'default_3x3', 'relax', 'Entspannen', 1, 49, 1, 0, 27, '1', '1', '0', '0', '', '', '', 'rela_header_en', 'rela_teaser_en', 'Entspannen Sie sich nach einem ereignisreichen Tag in der Welcome Lounge. Zünden Sie ein paar Kerzen an und entspannen Sie sich bei einer guten Lektüre auf einem Korbstuhl. Wir verstehen die Bedürfnisse eines Wulles mit einem hektischen Lebensstil!', '', '');
INSERT INTO `catalog_pages` VALUES (35, 209, 'default_3x3', 'romantique', 'Romantisch', 1, 50, 1, 0, 93, '1', '1', '0', '0', '', '', '', 'catalog_romantique_headline1', 'catalog_rom_teaser_en', 'Diese süße und dennoch sexuell romantische Serie, die in einer französischen Scheune gefunden wurde, erfüllt die Bedürfnisse aller Frauen. Ich werde mir nur die Nase abstauben!', '', '');
INSERT INTO `catalog_pages` VALUES (36, 209, 'default_3x3', 'scifi', 'Scifi', 1, 53, 1, 0, 99, '1', '1', '0', '0', '', '', '', 'sf_header_en', 'sf_teaser_en', 'Science-Fiction-Convention, Weltraum, Mond, wir haben alles, was Sie brauchen, um hier Ihren eigenen mystischen, nicht-irdischen Raum zu schaffen!', '', '');
INSERT INTO `catalog_pages` VALUES (37, 2211334, 'default_3x3', 'buy_badges', 'Badges', 1, 197, 1, 0, 10, '0', '1', '0', '0', NULL, '', '', '', 'catalog_teaser_new', NULL, '', '');
INSERT INTO `catalog_pages` VALUES (38, 219, 'default_3x3', 'freeze!', 'Freeze!', 1, 87, 1, 0, 5, '1', '1', '0', '0', NULL, '', '', 'catalog_freeze_en', 'ctlg_teaser_es', 'Gefriert! ... und probiere das neueste Spiel aus, um Wulles zu treffen! Bilden Sie ein Team und pflanzen Sie Schneeballpumpen, um Ihre Konkurrenten einzufrieren. Man könnte sagen, es ist großartig, es ist gefroren ;)', '', '');
INSERT INTO `catalog_pages` VALUES (40, 603, 'default_3x3', 'ads_room_backgrounds', 'Hintergründe', 5, 47, 1, 0, 6, '1', '1', '0', '0', NULL, '', '', '', '', 'Verwenden Sie sie, um Bilder in Ihrem Zimmer zu platzieren. Die mpus gehen zu einem Link, wenn Sie darauf klicken; AD&#039;s nicht.', '', '');
INSERT INTO `catalog_pages` VALUES (41, 387, 'default_3x3', 'theatredome', 'Theaterkuppel', 1, 927, 1, 0, 25, '1', '1', '0', '0', '', '', '', 'catalog_header_classics', 'article_habboreport2', 'Das Theatredrome ist ein sehr alter und beliebter öffentlicher Raum. Es hat viele Kampagnen von zahlenden Sponsoren gehostet.', '', '');
INSERT INTO `catalog_pages` VALUES (42, 568, 'default_3x3', 'rollers', 'Roller', 1, 222, 1, 0, 6, '1', '1', '0', '0', NULL, '', '', 'catalog_roller_headline1', 'catalog_teaser_rollers_en', 'Bewegen Sie Ihre Fantasie. Diese interessanten Dinge sind mehr als geeignet für Geschäft und Vergnügen... Habbo-Rollen für Spiele und Warteschlangen. Jetzt im Multipack erhältlich.', '', '');
INSERT INTO `catalog_pages` VALUES (44, 209, 'default_3x3', 'twilight', 'Twilight', 1, 52, 1, 0, 116, '1', '1', '0', '0', NULL, '', '', 'catalog_twilight_header_en', 'ctlg_pic_ads_twi_mist', 'Ich habe das Buch nie gelesen, alles, was ich weiß, ist, dass es Vampire gibt, die Basketball spielen, und einen Herzensbrecher namens Edward Cullen, aber die Möbel sehen gut aus!', '', '');
INSERT INTO `catalog_pages` VALUES (45, 219, 'default_3x3', 'battle_banzai', 'Battle Banzai', 1, 78, 1, 0, 3, '1', '1', '0', '0', NULL, '', '', 'catalog_battleBanzai_header_en', 'catalog_battleBanzai_teaser', 'Größer, besser, sprunghafter: Es ist Battle Banzai! Jetzt legst DU die Regeln deines eigenen Spiels fest, in deinem eigenen Zimmer. Du hast die Banzai-Macht!', '', '');
INSERT INTO `catalog_pages` VALUES (46, 253, 'default_3x3', 'trax', 'Trax', 1, 257, 1, 0, 21, '1', '1', '0', '0', '', 'Solo para decoración. Ellos no funcionan.', '', 'hotelhits_catalog_header', 'hotelhits_teaser', 'Trax sind Habbo-Musikscheiben, auf denen viele Melodien installiert sind, die auf einem Trax-Automaten im Raum abgespielt werden können. Nach dem Übergang von Habbo von Shockwave zu Flash-Clients wurde das trax-System erst im April 2011 wiederhergestellt, als nur Juke Boxen, alte CDs und von Habbo verkaufte CDs wiederveröffentlicht wurden.', '', '');
INSERT INTO `catalog_pages` VALUES (48, 568, 'default_3x3', 'pixels', 'Bildpunkte', 1, 5, 1, 0, 4, '1', '1', '0', '0', '', '', '', 'tienda-pixel', 'pixel3', '', '', '');
INSERT INTO `catalog_pages` VALUES (50, 568, 'default_3x3', 'automoviles', 'Auto', 1, 5, 1, 0, 2, '1', '1', '0', '0', '', '', '', 'tienda-pixel', 'pixel3', '', '', '');
INSERT INTO `catalog_pages` VALUES (51, 209, 'default_3x3', 'organo', 'Orgie', 1, 235, 1, 0, 81, '1', '1', '0', '0', '', '', '', 'organo_cata_header', 'organo_teaser', 'Ann Summers\' neueste Serie, die Orgie-Linie. Hergestellt aus weichem Kunststoff, der mit einem Tuch abgewischt wird, ist es perfekt für drei, vier oder fünf!', '', '');





INSERT INTO `catalog_pages` VALUES (32, 209, 'default_3x3', 'lost_tribe', 'Ramos perdidos', 1, 38, 1, 0, 121, '1', '1', '0', '0', '', '', '', 'losttribe', 'LT_teaser_en', 'Comience su propia aldea tribal con nuestros muebles antiguos, todos tallados en piedra robusta. NOTA: La lava es caliente, pida a un adulto que le ayude.', '', '');
INSERT INTO `catalog_pages` VALUES (33, 209, 'default_3x3', 'neon', 'Neon', 1, 41, 1, 0, 77, '1', '1', '0', '0', '', '', '', 'catalog_neon_header1_en', 'catalog_neon_teaser1_en', 'Los amantes de la fiesta están encantados! Coloque la piedra angular y agarre a los láseres con la serie Neon Furniture , todo lo que necesita para comenzar la fiesta!', '', '');
INSERT INTO `catalog_pages` VALUES (34, 209, 'default_3x3', 'relax', 'Relájese', 1, 49, 1, 0, 27, '1', '1', '0', '0', '', '', '', 'rela_header_en', 'rela_teaser_en', 'Relájese después de un día lleno de eventos en el salón de bienvenida. Encienda unas velas y relájese con una buena lectura en una silla de cesta. Entendemos las necesidades de un gusano con un estilo de vida frenético.', '', '');
INSERT INTO `catalog_pages` VALUES (35, 209, 'default_3x3', 'romantique', 'Romántico', 1, 50, 1, 0, 93, '1', '1', '0', '0', '', '', '', 'catalog_romantique_headline1', 'catalog_rom_teaser_en', 'Esta dulce y sin embargo sexualmente romántica serie, encontrada en un granero francés, satisface las necesidades de todas las mujeres.', '', '');
INSERT INTO `catalog_pages` VALUES (36, 209, 'default_3x3', 'scifi', 'Scifi', 1, 53, 1, 0, 99, '1', '1', '0', '0', '', '', '', 'sf_header_en', 'sf_teaser_en', '¡Convención de ciencia ficción, espacio, luna, tenemos todo lo que necesita para crear su propio espacio místico, no terrenal!', '', '');
INSERT INTO `catalog_pages` VALUES (37, 2211334, 'default_3x3', 'buy_badges', 'Badges', 1, 197, 1, 0, 10, '0', '1', '0', '0', NULL, '', '', '', 'catalog_teaser_new', NULL, '', '');
INSERT INTO `catalog_pages` VALUES (38, 219, 'default_3x3', 'freeze!', 'Freeze!', 1, 87, 1, 0, 5, '1', '1', '0', '0', NULL, '', '', 'catalog_freeze_en', 'ctlg_teaser_es', 'Gefriert! ... und probiere das neueste Spiel aus, um Wulles zu treffen! Bilden Sie ein Team und pflanzen Sie Schneeballpumpen, um Ihre Konkurrenten einzufrieren. Man könnte sagen, es ist großartig, es ist gefroren ;)', '', '');
INSERT INTO `catalog_pages` VALUES (40, 603, 'default_3x3', 'ads_room_backgrounds', 'Hintergründe', 5, 47, 1, 0, 6, '1', '1', '0', '0', NULL, '', '', '', '', 'Verwenden Sie sie, um Bilder in Ihrem Zimmer zu platzieren. Die mpus gehen zu einem Link, wenn Sie darauf klicken; AD&#039;s nicht.', '', '');
INSERT INTO `catalog_pages` VALUES (41, 387, 'default_3x3', 'theatredome', 'cúpula teatral', 1, 927, 1, 0, 25, '1', '1', '0', '0', '', '', '', 'catalog_header_classics', 'article_habboreport2', 'El Theatredrome es un espacio público muy antiguo y popular. Ha hospedado muchas campañas de patrocinadores de pago.', '', '');
INSERT INTO `catalog_pages` VALUES (42, 568, 'default_3x3', 'rollers', 'Roller', 1, 222, 1, 0, 6, '1', '1', '0', '0', NULL, '', '', 'catalog_roller_headline1', 'catalog_teaser_rollers_en', 'Bewegen Sie Ihre Fantasie. Diese interessanten Dinge sind mehr als geeignet für Geschäft und Vergnügen... Habbo-Rollen für Spiele und Warteschlangen. Jetzt im Multipack erhältlich.', '', '');
INSERT INTO `catalog_pages` VALUES (44, 209, 'default_3x3', 'twilight', 'Twilight', 1, 52, 1, 0, 116, '1', '1', '0', '0', NULL, '', '', 'catalog_twilight_header_en', 'ctlg_pic_ads_twi_mist', 'Ich habe das Buch nie gelesen, alles, was ich weiß, ist, dass es Vampire gibt, die Basketball spielen, und einen Herzensbrecher namens Edward Cullen, aber die Möbel sehen gut aus!', '', '');
INSERT INTO `catalog_pages` VALUES (45, 219, 'default_3x3', 'battle_banzai', 'Battle Banzai', 1, 78, 1, 0, 3, '1', '1', '0', '0', NULL, '', '', 'catalog_battleBanzai_header_en', 'catalog_battleBanzai_teaser', 'Größer, besser, sprunghafter: Es ist Battle Banzai! Jetzt legst DU die Regeln deines eigenen Spiels fest, in deinem eigenen Zimmer. Du hast die Banzai-Macht!', '', '');
INSERT INTO `catalog_pages` VALUES (46, 253, 'default_3x3', 'trax', 'Trax', 1, 257, 1, 0, 21, '1', '1', '0', '0', '', 'Solo para decoración. Ellos no funcionan.', '', 'hotelhits_catalog_header', 'hotelhits_teaser', 'Trax son discos de música Habbo en los que se instalan muchas melodías que se pueden reproducir en una máquina automática Trax en la habitación. Después de pasar de Habbo de Shockwave a Flash Clients, el sistema Trax no fue restaurado hasta abril de 2011, cuando solo se republicaron las cajas juke, los CDs antiguos y los CDs vendidos por Habbo.', '', '');
INSERT INTO `catalog_pages` VALUES (48, 568, 'default_3x3', 'pixels', 'Puntos de imagen', 1, 5, 1, 0, 4, '1', '1', '0', '0', '', '', '', 'tienda-pixel', 'pixel3', '', '', '');
INSERT INTO `catalog_pages` VALUES (50, 568, 'default_3x3', 'automoviles', 'Auto', 1, 5, 1, 0, 2, '1', '1', '0', '0', '', '', '', 'tienda-pixel', 'pixel3', '', '', '');
INSERT INTO `catalog_pages` VALUES (51, 209, 'default_3x3', 'organo', 'Orgía', 1, 235, 1, 0, 81, '1', '1', '0', '0', '', '', '', 'organo_cata_header', 'organo_teaser', 'Ann Summers\' neueste Serie, die Orgie-Linie. Hergestellt aus weichem Kunststoff, der mit einem Tuch abgewischt wird, ist es perfekt für drei, vier oder fünf!', '', '');
